//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IntegrationDoc;
using System.Runtime.Serialization;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[XmlInclude(typeof(Trans))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[System.Xml.Serialization.XmlRootAttribute("tempStorageRequest", Namespace = "http://egov.bee.kz/eds/tempstorage/v2/", IsNullable = false)]

public partial class TempStorageRequest
{
    private TempStorageRequestType typeField;
    private UploadFileRequest[] uploadRequestField;
    private string[] downloadRequestField;
    private string[] confirmRequestField;
    private string[] getFileInfoRequestField;
    private SenderInfo credentialsField;
    public TempStorageRequestType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    [System.Xml.Serialization.XmlArrayItemAttribute("fileUploadRequests", IsNullable = false)]
    public UploadFileRequest[] uploadRequest
    {
        get
        {
            return this.uploadRequestField;
        }
        set
        {
            this.uploadRequestField = value;
        }
    }
    [System.Xml.Serialization.XmlArrayItemAttribute("fileIdentifiers", IsNullable = false)]
    public string[] downloadRequest
    {
        get
        {
            return this.downloadRequestField;
        }
        set
        {
            this.downloadRequestField = value;
        }
    }
    [System.Xml.Serialization.XmlArrayItemAttribute("fileIdentifiers", IsNullable = false)]
    public string[] confirmRequest
    {
        get
        {
            return this.confirmRequestField;
        }
        set
        {
            this.confirmRequestField = value;
        }
    }
    [System.Xml.Serialization.XmlArrayItemAttribute("fileIdentifiers", IsNullable = false)]
    public string[] getFileInfoRequest
    {
        get
        {
            return this.getFileInfoRequestField;
        }
        set
        {
            this.getFileInfoRequestField = value;
        }
    }
    public SenderInfo credentials
    {
        get
        {
            return this.credentialsField;
        }
        set
        {
            this.credentialsField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public enum TempStorageRequestType
{
    UPLOAD,
    DOWNLOAD,
    CONFIRM,
    GET_FILE_INFO,
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class UploadFileRequest
{
    private string fileProcessIdentifierField;
    private byte[] contentField;
    private string nameField;
    private string mimeField;
    private long lifeTimeField;
    private bool lifeTimeFieldSpecified;
    private bool needToBeConfirmedField;
    private bool needToBeConfirmedFieldSpecified;
    public string fileProcessIdentifier
    {
        get
        {
            return this.fileProcessIdentifierField;
        }
        set
        {
            this.fileProcessIdentifierField = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    public string mime
    {
        get
        {
            return this.mimeField;
        }
        set
        {
            this.mimeField = value;
        }
    }
    public long lifeTime
    {
        get
        {
            return this.lifeTimeField;
        }
        set
        {
            this.lifeTimeField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lifeTimeSpecified
    {
        get
        {
            return this.lifeTimeFieldSpecified;
        }
        set
        {
            this.lifeTimeFieldSpecified = value;
        }
    }
    public bool needToBeConfirmed
    {
        get
        {
            return this.needToBeConfirmedField;
        }
        set
        {
            this.needToBeConfirmedField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool needToBeConfirmedSpecified
    {
        get
        {
            return this.needToBeConfirmedFieldSpecified;
        }
        set
        {
            this.needToBeConfirmedFieldSpecified = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class FileInfoResult
{
    private ProcessStatus statusField;
    private string fileIdentifierField;
    private FileInfo metaField;
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    public string fileIdentifier
    {
        get
        {
            return this.fileIdentifierField;
        }
        set
        {
            this.fileIdentifierField = value;
        }
    }
    public FileInfo meta
    {
        get
        {
            return this.metaField;
        }
        set
        {
            this.metaField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class ProcessStatus
{
    private string codeField;
    private string statusField;
    private string messageField;
    [DataMember]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    [DataMember]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    [DataMember]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class FileInfo
{
    private string nameField;
    private string mimeField;
    private System.DateTime uploadDateField;
    private System_ uploaderSystemField;
    private System.DateTime expirationTimeField;
    private bool needToBeConfirmedField;
    private bool needToBeConfirmedFieldSpecified;
    private long sizeField;
    private bool deletedField;
    private System.DateTime deletionTimeField;
    private bool deletionTimeFieldSpecified;
    private bool confirmedField;
    private System_ confirmedSystemField;
    private System.DateTime confirmationTimeField;
    private bool confirmationTimeFieldSpecified;
    [DataMember]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    [DataMember]
    public string mime
    {
        get
        {
            return this.mimeField;
        }
        set
        {
            this.mimeField = value;
        }
    }
    [DataMember(EmitDefaultValue = false, IsRequired = false)]
    public System.DateTime uploadDate
    {
        get
        {
            return this.uploadDateField;
        }
        set
        {
            this.uploadDateField = value;
        }
    }
    [DataMember]
    public System_ uploaderSystem
    {
        get
        {
            return this.uploaderSystemField;
        }
        set
        {
            this.uploaderSystemField = value;
        }
    }
    [DataMember(EmitDefaultValue = false, IsRequired = false)]
    public System.DateTime expirationTime
    {
        get
        {
            return this.expirationTimeField;
        }
        set
        {
            this.expirationTimeField = value;
        }
    }
    [DataMember]
    public bool needToBeConfirmed
    {
        get
        {
            return this.needToBeConfirmedField;
        }
        set
        {
            this.needToBeConfirmedField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool needToBeConfirmedSpecified
    {
        get
        {
            return this.needToBeConfirmedFieldSpecified;
        }
        set
        {
            this.needToBeConfirmedFieldSpecified = value;
        }
    }
    [DataMember]
    public long size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }
    [DataMember]
    public bool deleted
    {
        get
        {
            return this.deletedField;
        }
        set
        {
            this.deletedField = value;
        }
    }
    [DataMember(EmitDefaultValue = false, IsRequired = false)]
    public System.DateTime deletionTime
    {
        get
        {
            return this.deletionTimeField;
        }
        set
        {
            this.deletionTimeField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deletionTimeSpecified
    {
        get
        {
            return this.deletionTimeFieldSpecified;
        }
        set
        {
            this.deletionTimeFieldSpecified = value;
        }
    }
    [DataMember]
    public bool confirmed
    {
        get
        {
            return this.confirmedField;
        }
        set
        {
            this.confirmedField = value;
        }
    }
    [DataMember]
    public System_ confirmedSystem
    {
        get
        {
            return this.confirmedSystemField;
        }
        set
        {
            this.confirmedSystemField = value;
        }
    }
    [DataMember(EmitDefaultValue =false,IsRequired =false)]
    public System.DateTime confirmationTime
    {
        get
        {
            return this.confirmationTimeField;
        }
        set
        {
            this.confirmationTimeField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool confirmationTimeSpecified
    {
        get
        {
            return this.confirmationTimeFieldSpecified;
        }
        set
        {
            this.confirmationTimeFieldSpecified = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class System_
{
    private string idField;
    [DataMember]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class GetFileInfoResponse
{
    private FileInfoResult[] fileInfoResultsField;
    private ProcessStatus statusField;
    [System.Xml.Serialization.XmlElementAttribute("fileInfoResults")]
    public FileInfoResult[] fileInfoResults
    {
        get
        {
            return this.fileInfoResultsField;
        }
        set
        {
            this.fileInfoResultsField = value;
        }
    }
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class FileConfirmResult
{
    private ProcessStatus statusField;
    private string fileIdentifierField;
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    public string fileIdentifier
    {
        get
        {
            return this.fileIdentifierField;
        }
        set
        {
            this.fileIdentifierField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class ConfirmResponse
{
    private FileConfirmResult[] fileConfirmResultsField;
    private ProcessStatus statusField;
    [System.Xml.Serialization.XmlElementAttribute("fileConfirmResults")]
    public FileConfirmResult[] fileConfirmResults
    {
        get
        {
            return this.fileConfirmResultsField;
        }
        set
        {
            this.fileConfirmResultsField = value;
        }
    }
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class FileDownloadResult
{
    private ProcessStatus statusField;
    private string fileIdentifierField;
    private byte[] contentField;
    private FileInfo metaField;
    [DataMember]
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    [DataMember]
    public string fileIdentifier
    {
        get
        {
            return this.fileIdentifierField;
        }
        set
        {
            this.fileIdentifierField = value;
        }
    }
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    [DataMember]
    public byte[] content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }
    [DataMember]
    public FileInfo meta
    {
        get
        {
            return this.metaField;
        }
        set
        {
            this.metaField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class DownloadResponse
{
    private FileDownloadResult[] fileDownloadResultsField;
    private ProcessStatus statusField;
    [System.Xml.Serialization.XmlElementAttribute("fileDownloadResults")]
    [DataMember]
    public FileDownloadResult[] fileDownloadResults
    {
        get
        {
            return this.fileDownloadResultsField;
        }
        set
        {
            this.fileDownloadResultsField = value;
        }
    }
    [DataMember]
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class FileUploadResult
{
    private string fileProcessIdentifierField;
    private ProcessStatus statusField;
    private string fileIdentifierField;
    private long lifeTimeField;
    private bool lifeTimeFieldSpecified;
    [DataMember]
    public string fileProcessIdentifier
    {
        get
        {
            return this.fileProcessIdentifierField;
        }
        set
        {
            this.fileProcessIdentifierField = value;
        }
    }
    [DataMember]
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    [DataMember]
    public string fileIdentifier
    {
        get
        {
            return this.fileIdentifierField;
        }
        set
        {
            this.fileIdentifierField = value;
        }
    }
    [DataMember]
    public long lifeTime
    {
        get
        {
            return this.lifeTimeField;
        }
        set
        {
            this.lifeTimeField = value;
        }
    }
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lifeTimeSpecified
    {
        get
        {
            return this.lifeTimeFieldSpecified;
        }
        set
        {
            this.lifeTimeFieldSpecified = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[DataContract]
public partial class UploadResponse
{
    private FileUploadResult[] uploadFileResultsField;
    private ProcessStatus statusField;
    [System.Xml.Serialization.XmlElementAttribute("uploadFileResults")]
    [DataMember]
    public FileUploadResult[] uploadFileResults
    {
        get
        {
            return this.uploadFileResultsField;
        }
        set
        {
            this.uploadFileResultsField = value;
        }
    }
    [DataMember]
    public ProcessStatus status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bee.kz/eds/tempstorage/v2/")]
public partial class SenderInfo
{
    private string senderIdField;
    private string passwordField;
    public string senderId
    {
        get
        {
            return this.senderIdField;
        }
        set
        {
            this.senderIdField = value;
        }
    }
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://egov.bee.kz/eds/tempstorage/v2/")]
[System.Xml.Serialization.XmlRootAttribute("tempStorageResponse", Namespace = "http://egov.bee.kz/eds/tempstorage/v2/", IsNullable = false)]
[DataContract]
public partial class TempStorageResponse
{
    private TempStorageRequestType typeField;
    private UploadResponse uploadResponseField;
    private DownloadResponse downloadResponseField;
    private ConfirmResponse confirmResponseField;
    private GetFileInfoResponse getFileInfoResponseField;
    [DataMember]
    public TempStorageRequestType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    [DataMember]
    public UploadResponse uploadResponse
    {
        get
        {
            return this.uploadResponseField;
        }
        set
        {
            this.uploadResponseField = value;
        }
    }
    [DataMember]
    public DownloadResponse downloadResponse
    {
        get
        {
            return this.downloadResponseField;
        }
        set
        {
            this.downloadResponseField = value;
        }
    }
    [DataMember]
    public ConfirmResponse confirmResponse
    {
        get
        {
            return this.confirmResponseField;
        }
        set
        {
            this.confirmResponseField = value;
        }
    }
    [DataMember]
    public GetFileInfoResponse getFileInfoResponse
    {
        get
        {
            return this.getFileInfoResponseField;
        }
        set
        {
            this.getFileInfoResponseField = value;
        }
    }
}
