//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationDoc.NsiSync {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://isate.kz/ensi/dictionary", ConfigurationName="NsiSync.DictionaryPort")]
    public interface DictionaryPort {
        
        // CODEGEN: Generating message contract since the operation GetDictionary is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PRActionWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PostWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeopleCategoryWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationTypeWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrganizationWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExecutionResultWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentTypeWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentReasonWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentCharacterWrapper))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ControlTypeWrapper))]
        IntegrationDoc.NsiSync.GetDictionaryResponse1 GetDictionary(IntegrationDoc.NsiSync.GetDictionaryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationDoc.NsiSync.GetDictionaryResponse1> GetDictionaryAsync(IntegrationDoc.NsiSync.GetDictionaryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isate.kz/ensi/dictionary")]
    public partial class GetDictionaryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderField;
        
        private dictionary[] dictionariesField;
        
        private System.Nullable<System.DateTime> currentDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dictionaries", Order=1)]
        public dictionary[] dictionaries {
            get {
                return this.dictionariesField;
            }
            set {
                this.dictionariesField = value;
                this.RaisePropertyChanged("dictionaries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> currentDate {
            get {
                return this.currentDateField;
            }
            set {
                this.currentDateField = value;
                this.RaisePropertyChanged("currentDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/dictionary")]
    public partial class dictionary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.DateTime lastUpdateDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime lastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
                this.RaisePropertyChanged("lastUpdateDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class Region : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private string region_typeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string region_type {
            get {
                return this.region_typeField;
            }
            set {
                this.region_typeField = value;
                this.RaisePropertyChanged("region_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class RegionWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private Region[] nSI_REGIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_REGIONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Region[] NSI_REGIONS {
            get {
                return this.nSI_REGIONSField;
            }
            set {
                this.nSI_REGIONSField = value;
                this.RaisePropertyChanged("NSI_REGIONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class PRAction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class PRActionWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private PRAction[] nSI_ACTIONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_ACTIONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PRAction[] NSI_ACTIONS {
            get {
                return this.nSI_ACTIONSField;
            }
            set {
                this.nSI_ACTIONSField = value;
                this.RaisePropertyChanged("NSI_ACTIONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class Post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class PostWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private Post[] nSI_POS_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_POS_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Post[] NSI_POS_TYPE {
            get {
                return this.nSI_POS_TYPEField;
            }
            set {
                this.nSI_POS_TYPEField = value;
                this.RaisePropertyChanged("NSI_POS_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class PeopleCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class PeopleCategoryWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private PeopleCategory[] nSI_APPLICANTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_APPLICANT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PeopleCategory[] NSI_APPLICANT {
            get {
                return this.nSI_APPLICANTField;
            }
            set {
                this.nSI_APPLICANTField = value;
                this.RaisePropertyChanged("NSI_APPLICANT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class OrganizationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class OrganizationTypeWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private OrganizationType[] nSI_ORG_TYPESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_ORG_TYPES", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OrganizationType[] NSI_ORG_TYPES {
            get {
                return this.nSI_ORG_TYPESField;
            }
            set {
                this.nSI_ORG_TYPESField = value;
                this.RaisePropertyChanged("NSI_ORG_TYPES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class Organization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string ensiIdField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string abbr_ruField;
        
        private string abbr_kzField;
        
        private System.Nullable<decimal> memberField;
        
        private string codeField;
        
        private bool isMarkedToDeleteField;
        
        private string isEsedoField;
        
        private string isReadyField;
        
        private string parentField;
        
        private string childsCountField;
        
        private decimal elementGUIDField;
        
        private string qGIdentifierField;
        
        private string addressField;
        
        private string phoneNumberField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string EnsiId {
            get {
                return this.ensiIdField;
            }
            set {
                this.ensiIdField = value;
                this.RaisePropertyChanged("EnsiId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string abbr_ru {
            get {
                return this.abbr_ruField;
            }
            set {
                this.abbr_ruField = value;
                this.RaisePropertyChanged("abbr_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string abbr_kz {
            get {
                return this.abbr_kzField;
            }
            set {
                this.abbr_kzField = value;
                this.RaisePropertyChanged("abbr_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<decimal> member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
                this.RaisePropertyChanged("member");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string isEsedo {
            get {
                return this.isEsedoField;
            }
            set {
                this.isEsedoField = value;
                this.RaisePropertyChanged("isEsedo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string isReady {
            get {
                return this.isReadyField;
            }
            set {
                this.isReadyField = value;
                this.RaisePropertyChanged("isReady");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=11)]
        public string Parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
                this.RaisePropertyChanged("Parent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=12)]
        public string ChildsCount {
            get {
                return this.childsCountField;
            }
            set {
                this.childsCountField = value;
                this.RaisePropertyChanged("ChildsCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string QGIdentifier {
            get {
                return this.qGIdentifierField;
            }
            set {
                this.qGIdentifierField = value;
                this.RaisePropertyChanged("QGIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class OrganizationWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private Organization[] nSI_ORGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ORG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Organization[] NSI_ORG {
            get {
                return this.nSI_ORGField;
            }
            set {
                this.nSI_ORGField = value;
                this.RaisePropertyChanged("ORG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class ExecutionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private string categoryField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class ExecutionResultWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private ExecutionResult[] nSI_EXRES_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_EXRES_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ExecutionResult[] NSI_EXRES_TYPE {
            get {
                return this.nSI_EXRES_TYPEField;
            }
            set {
                this.nSI_EXRES_TYPEField = value;
                this.RaisePropertyChanged("NSI_EXRES_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class DocumentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class DocumentTypeWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private DocumentType[] nSI_DOC_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_DOC_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DocumentType[] NSI_DOC_TYPE {
            get {
                return this.nSI_DOC_TYPEField;
            }
            set {
                this.nSI_DOC_TYPEField = value;
                this.RaisePropertyChanged("NSI_DOC_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class DocumentReason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class DocumentReasonWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private DocumentReason[] nSI_REASONSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_REASONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DocumentReason[] NSI_REASONS {
            get {
                return this.nSI_REASONSField;
            }
            set {
                this.nSI_REASONSField = value;
                this.RaisePropertyChanged("NSI_REASONS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class DocumentCharacter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class DocumentCharacterWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private DocumentCharacter[] nSI_CHARACTERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_CHARACTERS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DocumentCharacter[] NSI_CHARACTERS {
            get {
                return this.nSI_CHARACTERSField;
            }
            set {
                this.nSI_CHARACTERSField = value;
                this.RaisePropertyChanged("NSI_CHARACTERS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/entity")]
    public partial class ControlType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool isMarkedToDeleteField;
        
        private string name_ruField;
        
        private string name_kzField;
        
        private string codeField;
        
        private string daysField;
        
        private decimal elementGUIDField;
        
        private System.DateTime update_dateField;
        
        private bool update_dateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool IsMarkedToDelete {
            get {
                return this.isMarkedToDeleteField;
            }
            set {
                this.isMarkedToDeleteField = value;
                this.RaisePropertyChanged("IsMarkedToDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ru {
            get {
                return this.name_ruField;
            }
            set {
                this.name_ruField = value;
                this.RaisePropertyChanged("name_ru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name_kz {
            get {
                return this.name_kzField;
            }
            set {
                this.name_kzField = value;
                this.RaisePropertyChanged("name_kz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
                this.RaisePropertyChanged("days");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ElementGUID {
            get {
                return this.elementGUIDField;
            }
            set {
                this.elementGUIDField = value;
                this.RaisePropertyChanged("ElementGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime update_date {
            get {
                return this.update_dateField;
            }
            set {
                this.update_dateField = value;
                this.RaisePropertyChanged("update_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool update_dateSpecified {
            get {
                return this.update_dateFieldSpecified;
            }
            set {
                this.update_dateFieldSpecified = value;
                this.RaisePropertyChanged("update_dateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://isate.kz/ensi/wrapper")]
    public partial class ControlTypeWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityNameField;
        
        private string numberOfUpdatesField;
        
        private ControlType[] nSI_CONTROL_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string entityName {
            get {
                return this.entityNameField;
            }
            set {
                this.entityNameField = value;
                this.RaisePropertyChanged("entityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numberOfUpdates {
            get {
                return this.numberOfUpdatesField;
            }
            set {
                this.numberOfUpdatesField = value;
                this.RaisePropertyChanged("numberOfUpdates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NSI_CONTROL_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ControlType[] NSI_CONTROL_TYPE {
            get {
                return this.nSI_CONTROL_TYPEField;
            }
            set {
                this.nSI_CONTROL_TYPEField = value;
                this.RaisePropertyChanged("NSI_CONTROL_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://isate.kz/ensi/dictionary")]
    public partial class GetDictionaryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime currentDateField;
        
        private object[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime currentDate {
            get {
                return this.currentDateField;
            }
            set {
                this.currentDateField = value;
                this.RaisePropertyChanged("currentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", IsNullable=true, Order=1)]
        public object[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictionaryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isate.kz/ensi/dictionary", Order=0)]
        public IntegrationDoc.NsiSync.GetDictionaryRequest GetDictionaryRequest;
        
        public GetDictionaryRequest1() {
        }
        
        public GetDictionaryRequest1(IntegrationDoc.NsiSync.GetDictionaryRequest GetDictionaryRequest) {
            this.GetDictionaryRequest = GetDictionaryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictionaryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://isate.kz/ensi/dictionary", Order=0)]
        public IntegrationDoc.NsiSync.GetDictionaryResponse GetDictionaryResponse;
        
        public GetDictionaryResponse1() {
        }
        
        public GetDictionaryResponse1(IntegrationDoc.NsiSync.GetDictionaryResponse GetDictionaryResponse) {
            this.GetDictionaryResponse = GetDictionaryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictionaryPortChannel : IntegrationDoc.NsiSync.DictionaryPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictionaryPortClient : System.ServiceModel.ClientBase<IntegrationDoc.NsiSync.DictionaryPort>, IntegrationDoc.NsiSync.DictionaryPort {
        
        public DictionaryPortClient() {
        }
        
        public DictionaryPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictionaryPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionaryPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionaryPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationDoc.NsiSync.GetDictionaryResponse1 IntegrationDoc.NsiSync.DictionaryPort.GetDictionary(IntegrationDoc.NsiSync.GetDictionaryRequest1 request) {
            return base.Channel.GetDictionary(request);
        }
        
        public IntegrationDoc.NsiSync.GetDictionaryResponse GetDictionary(IntegrationDoc.NsiSync.GetDictionaryRequest GetDictionaryRequest) {
            IntegrationDoc.NsiSync.GetDictionaryRequest1 inValue = new IntegrationDoc.NsiSync.GetDictionaryRequest1();
            inValue.GetDictionaryRequest = GetDictionaryRequest;
            IntegrationDoc.NsiSync.GetDictionaryResponse1 retVal = ((IntegrationDoc.NsiSync.DictionaryPort)(this)).GetDictionary(inValue);
            return retVal.GetDictionaryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationDoc.NsiSync.GetDictionaryResponse1> IntegrationDoc.NsiSync.DictionaryPort.GetDictionaryAsync(IntegrationDoc.NsiSync.GetDictionaryRequest1 request) {
            return base.Channel.GetDictionaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationDoc.NsiSync.GetDictionaryResponse1> GetDictionaryAsync(IntegrationDoc.NsiSync.GetDictionaryRequest GetDictionaryRequest) {
            IntegrationDoc.NsiSync.GetDictionaryRequest1 inValue = new IntegrationDoc.NsiSync.GetDictionaryRequest1();
            inValue.GetDictionaryRequest = GetDictionaryRequest;
            return ((IntegrationDoc.NsiSync.DictionaryPort)(this)).GetDictionaryAsync(inValue);
        }
    }
}
